// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAExPzW81dZOgI0Mz_GU53mgG3hwqExMk0',
    appId: '1:628559535793:web:06fc9b66f1951c1bd9cc90',
    messagingSenderId: '628559535793',
    projectId: 'mara-pub',
    authDomain: 'mara-pub.firebaseapp.com',
    storageBucket: 'mara-pub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDiS26ZLnyvat8KIbvhgwYvVoBddyGmFQ',
    appId: '1:628559535793:android:f66b9f5a147f7137d9cc90',
    messagingSenderId: '628559535793',
    projectId: 'mara-pub',
    storageBucket: 'mara-pub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCde169ecalVFtkFIe3fPEqpLXSmwgW8mc',
    appId: '1:628559535793:ios:58eb1012ab00af54d9cc90',
    messagingSenderId: '628559535793',
    projectId: 'mara-pub',
    storageBucket: 'mara-pub.firebasestorage.app',
    iosBundleId: 'com.example.maraPub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCde169ecalVFtkFIe3fPEqpLXSmwgW8mc',
    appId: '1:628559535793:ios:58eb1012ab00af54d9cc90',
    messagingSenderId: '628559535793',
    projectId: 'mara-pub',
    storageBucket: 'mara-pub.firebasestorage.app',
    iosBundleId: 'com.example.maraPub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAExPzW81dZOgI0Mz_GU53mgG3hwqExMk0',
    appId: '1:628559535793:web:32d7f2b2cdea6d04d9cc90',
    messagingSenderId: '628559535793',
    projectId: 'mara-pub',
    authDomain: 'mara-pub.firebaseapp.com',
    storageBucket: 'mara-pub.firebasestorage.app',
  );
}
